[package]
name = "burn_dinov3"
version = "0.1.2"
edition = "2024"
authors = ["kingwingfly <836250617@qq.com>"]
license = "MIT"
repository = "https://github.com/kingwingfly/burn_dinov3"
documentation = "https://docs.rs/burn_dinov3"
description = "DINOv3 with burn & Rust"
keywords = ["dinov3", "dino", "burn", "vit"]

[dependencies]
burn = "0.21"

[target.'cfg(target_os = "macos")'.dev-dependencies]
burn = { version = "0.21", features = ["metal"] }

[target.'cfg(not(target_os = "macos"))'.dev-dependencies]
burn = { version = "0.21", features = ["cuda"] }

[dev-dependencies]
burn-store = "0.21"
